### PR TITLE
hi

### PR DESCRIPTION
**Pull request by ItsPizzaTime1501**
I probably broke something, anyways enjoy frii mkdocs

### CODE REVIEW

**Comment by ItsPizzaTime1501** [comment]
https://friigaemsworld.com

**Comment by kriegisrei** [comment]
if this breaks everything im telling phaz to takehelp you yknow

**Comment by ItsPizzaTime1501** [comment]
waguspin

**Comment by ItsPizzaTime1501** [comment]
just merge it

**Pull request merged**
